var wordsToGuess = [
    'algorithm',
    'application',
    'analog',
    'backup',
    'binary',
    'browser',
    'command',
    'cyberspace',
    'development',
    'encryption',
    'firmware',
    'hardware',
    'home page',
    'hyperlink',
    'Internet',
    'Java',
    'keyword',
    'logic',
    'malware',
    'memory',
    'node',
    'operating system',
    'password',
    'protocol',
    'resolution',
    'router',
    'screenshot',
    'social networking',
    'Trojan horse',
    'Unix',
    'version',
    'virus',
    'webmaster',
    'World Wide Web'
];
var randoIndex = Math.floor(Math.random() * wordsToGuess.length);
var randoWord = wordsToGuess[randoIndex];
exports.randoWord = randoWord;